// server.js

const express = require('express');
const cors = require('cors');
const app = express();
const port = 3001;

app.use(cors()); // Enable CORS
app.use(express.json());

// Mock data
const movements = [
    { name: 'Running', caloriesPerMinute: 10 },
    { name: 'Pushups', caloriesPerRep: 0.5 },
    { name: 'Squats', caloriesPerRep: 0.6 },
    { name: 'Jumping Jacks', caloriesPerMinute: 8 },
    { name: 'Cycling', caloriesPerMinute: 12 },
    { name: 'Burpees', caloriesPerRep: 1 },
    { name: 'Swimming', caloriesPerMinute: 11 },
    { name: 'Sit-ups', caloriesPerRep: 0.7 },
    { name: 'Plank', caloriesPerMinute: 5 },
    { name: 'Pull-ups', caloriesPerRep: 1 },
    { name: 'Chest Press', caloriesPerRep: 0.7 },
    { name: 'Deadlifts', caloriesPerRep: 0.9 },
    { name: 'Bicycling', caloriesPerMinute: 9 },
    { name: 'Rowing', caloriesPerMinute: 10 },
    { name: 'Yoga', caloriesPerMinute: 6 },
    { name: 'Jump Rope', caloriesPerMinute: 12 },
    { name: 'Box Jumps', caloriesPerRep: 1.2 },
    { name: 'Leg Press', caloriesPerRep: 0.8 },
    { name: 'Mountain Climbers', caloriesPerMinute: 10 },
    { name: 'Lunges', caloriesPerRep: 0.7 },
    { name: 'Burpee Pull-ups', caloriesPerRep: 1.5 },
    { name: 'Boxing', caloriesPerMinute: 10 },
    { name: 'Kettlebell Swings', caloriesPerMinute: 12 },
    { name: 'Battle Ropes', caloriesPerMinute: 15 },
    { name: 'Jump Squats', caloriesPerRep: 1 },
    { name: 'High Knees', caloriesPerMinute: 11 },
    { name: 'Dumbbell Rows', caloriesPerRep: 0.8 },
    { name: 'Hiking', caloriesPerMinute: 8 },
    { name: 'Pilates', caloriesPerMinute: 7 },
    { name: 'Bench Press', caloriesPerRep: 0.8 },
    { name: 'Stair Climbing', caloriesPerMinute: 12 },
    { name: 'Tricep Dips', caloriesPerRep: 0.6 },
    { name: 'Russian Twists', caloriesPerRep: 0.5 },
    { name: 'Wall Sits', caloriesPerMinute: 4 },
    { name: 'Jumping Lunges', caloriesPerRep: 0.9 },
    { name: 'Calf Raises', caloriesPerRep: 0.5 },
    { name: 'Barbell Squats', caloriesPerRep: 1 },
    { name: 'Skaters', caloriesPerMinute: 9 },
    { name: 'Sprints', caloriesPerMinute: 12 },
    { name: 'Handstand Pushups', caloriesPerRep: 1 },
    { name: 'Rowing Machine', caloriesPerMinute: 9 },
    { name: 'Ab Rollouts', caloriesPerRep: 0.7 },
    { name: 'Jumping Rope Double Unders', caloriesPerMinute: 15 },
    { name: 'Kickboxing', caloriesPerMinute: 10 },
    { name: 'Dead Hang', caloriesPerMinute: 3 },
    { name: 'Incline Press', caloriesPerRep: 0.7 },
    { name: 'Flutter Kicks', caloriesPerMinute: 8 },
    { name: 'Jumping Spider Planks', caloriesPerMinute: 7 },
    { name: 'Sled Push', caloriesPerMinute: 12 },
    { name: 'Plyometric Pushups', caloriesPerRep: 0.8 },
    { name: 'Romanian Deadlifts', caloriesPerRep: 0.9 },
    { name: 'Lateral Lunges', caloriesPerRep: 0.8 },
    { name: 'Scissor Kicks', caloriesPerMinute: 8 },
    { name: 'Bicep Curls', caloriesPerRep: 0.6 },
    { name: 'Jumping Oblique Twists', caloriesPerRep: 0.7 },
    { name: 'Dumbbell Lunges', caloriesPerRep: 0.8 },
    { name: 'Zumba', caloriesPerMinute: 9 },
    { name: 'Plyometric Box Jumps', caloriesPerRep: 1.3 },
    { name: 'Push Press', caloriesPerRep: 0.9 },
    { name: 'Jumping High Kicks', caloriesPerRep: 0.8 },
    { name: 'Squat Jumps', caloriesPerRep: 1 },
    { name: 'Sumo Deadlifts', caloriesPerRep: 1 },
    { name: 'Jumping Knee Tucks', caloriesPerRep: 0.9 },
    { name: 'Dumbbell Shoulder Press', caloriesPerRep: 0.7 },
    { name: 'Bear Crawls', caloriesPerMinute: 9 },
    { name: 'Crab Walks', caloriesPerMinute: 8 },
    { name: 'Pistol Squats', caloriesPerRep: 0.8 },
    { name: 'Russian Kettlebell Swings', caloriesPerMinute: 13 },
    { name: 'Medicine Ball Slams', caloriesPerRep: 1.2 },
    { name: 'Bicycle Crunches', caloriesPerRep: 0.6 },
    { name: 'Jumping Jacks with Weights', caloriesPerMinute: 9 },
    { name: 'Pogo Hops', caloriesPerMinute: 10 },
    { name: 'Reverse Lunges', caloriesPerRep: 0.7 },
    { name: 'Plank Jacks', caloriesPerMinute: 6 },
    { name: 'Bulgarian Split Squats', caloriesPerRep: 0.8 },
    { name: 'Knee Tucks', caloriesPerRep: 0.7 },
    { name: 'Shoulder Taps', caloriesPerMinute: 6 },
    { name: 'Knee Pushups', caloriesPerRep: 0.4 },
    { name: 'Tuck Jumps', caloriesPerRep: 1.2 },
    { name: 'Lateral Band Walks', caloriesPerMinute: 7 },
    { name: 'Spider Lunges', caloriesPerRep: 0.8 },
    { name: 'Windshield Wipers', caloriesPerMinute: 7 },
    { name: 'Leg Raises', caloriesPerRep: 0.5 },
    { name: 'Skipping', caloriesPerMinute: 11 },
    { name: 'Russian Twists with Medicine Ball', caloriesPerMinute: 9 },
    { name: 'Cable Crunches', caloriesPerRep: 0.7 },
    { name: 'Hammer Curls', caloriesPerRep: 0.6 },
    { name: 'Back Extensions', caloriesPerRep: 0.5 },
    { name: 'Plank Up-Downs', caloriesPerMinute: 7 },
    { name: 'Standing Calf Raises', caloriesPerRep: 0.6 },
    { name: 'Stability Ball Rollouts', caloriesPerRep: 0.8 },
    { name: 'Step-ups', caloriesPerRep: 0.7 },
    { name: 'Walking Lunges', caloriesPerMinute: 7 },
    { name: 'Dips', caloriesPerRep: 0.6 },
    { name: 'Decline Pushups', caloriesPerRep: 0.6 },
    { name: 'Cable Rows', caloriesPerRep: 0.7 },
    { name: 'Jumping Squats with Weights', caloriesPerRep: 1.2 },
    { name: 'Single-Leg Deadlifts', caloriesPerRep: 0.8 },
    { name: 'Hollow Body Hold', caloriesPerMinute: 6 },
    { name: 'Seated Leg Press', caloriesPerRep: 0.8 },
    { name: 'Squat to Overhead Press', caloriesPerRep: 1 },
    { name: 'Clamshells', caloriesPerMinute: 5 },
    { name: 'Lateral Raises', caloriesPerRep: 0.5 },
    { name: 'Tricep Kickbacks', caloriesPerRep: 0.6 },
    { name: 'Side Planks', caloriesPerMinute: 5 },
    { name: 'Mountain Climbers with Sliders', caloriesPerMinute: 9 },
    { name: 'Alternating Dumbbell Curl', caloriesPerRep: 0.5 },
    { name: 'Overhead Tricep Extension', caloriesPerRep: 0.6 },
    { name: 'Jumping Oblique Crunches', caloriesPerRep: 0.7 },
    { name: 'Tricep Extensions', caloriesPerRep: 0.6 },
    { name: 'Hammer Curls', caloriesPerRep: 0.6 },
    { name: 'Dumbbell Flyes', caloriesPerRep: 0.7 },
    { name: 'Leg Curls', caloriesPerRep: 0.7 },
    { name: 'Deadlifts', caloriesPerRep: 0.9 },
    { name: 'Pull-ups', caloriesPerRep: 1 },
    { name: 'Chin-ups', caloriesPerRep: 1 },
    { name: 'Bent Over Rows', caloriesPerRep: 0.8 },
    { name: 'Chest Dips', caloriesPerRep: 0.7 },
    { name: 'Push Press', caloriesPerRep: 0.9 },
    { name: 'Arnold Press', caloriesPerRep: 0.7 },
    { name: 'Lateral Raises', caloriesPerRep: 0.5 },
    { name: 'Front Raises', caloriesPerRep: 0.6 },
    { name: 'Leg Press', caloriesPerRep: 0.8 },
    { name: 'Leg Extensions', caloriesPerRep: 0.7 },
    { name: 'Calf Raises', caloriesPerRep: 0.5 },
    { name: 'Seated Calf Raises', caloriesPerRep: 0.6 },
    { name: 'Back Extensions', caloriesPerRep: 0.5 },
    { name: 'Good Mornings', caloriesPerRep: 0.8 },
    { name: 'Barbell Shrugs', caloriesPerRep: 0.7 },
    { name: 'Dumbbell Pullovers', caloriesPerRep: 0.6 },
    { name: 'Dumbbell Bench Press', caloriesPerRep: 0.8 },
    { name: 'Incline Bench Press', caloriesPerRep: 0.7 },
    { name: 'Decline Bench Press', caloriesPerRep: 0.7 },
    { name: 'Chest Flyes', caloriesPerRep: 0.7 },
    { name: 'Wide Grip Bench Press', caloriesPerRep: 0.8 },
    { name: 'Close Grip Bench Press', caloriesPerRep: 0.8 },
    { name: 'Standing Military Press', caloriesPerRep: 0.8 },
    { name: 'Dumbbell Shoulder Press', caloriesPerRep: 0.7 },
    { name: 'Reverse Flyes', caloriesPerRep: 0.6 },
    { name: 'Leg Press Calf Raises', caloriesPerRep: 0.6 },
    { name: 'Roman Chair Leg Raises', caloriesPerRep: 0.7 },
    { name: 'Seated Leg Curls', caloriesPerRep: 0.7 },
    { name: 'One Arm Dumbbell Rows', caloriesPerRep: 0.8 },
    { name: 'Cable Rows', caloriesPerRep: 0.7 },
    { name: 'Lat Pulldowns', caloriesPerRep: 0.8 },
    { name: 'Reverse Grip Barbell Rows', caloriesPerRep: 0.8 },
    { name: 'Standing Calf Raises', caloriesPerRep: 0.6 },
    { name: 'Cable Crossover', caloriesPerRep: 0.7 },
    { name: 'Dumbbell Pullovers', caloriesPerRep: 0.6 },
    { name: 'Seated Rows', caloriesPerRep: 0.7 },
    { name: 'Straight Arm Pulldowns', caloriesPerRep: 0.6 },
    { name: 'Close Grip Pulldowns', caloriesPerRep: 0.7 },
    { name: 'Bent Over Reverse Flyes', caloriesPerRep: 0.6 },
    { name: 'Pullovers', caloriesPerRep: 0.6 },
    { name: 'Leg Press Calf Raises', caloriesPerRep: 0.6 },
    { name: 'Roman Chair Leg Raises', caloriesPerRep: 0.7 },
    { name: 'Cable Crunches', caloriesPerRep: 0.7 },
    { name: 'Standing Barbell Calf Raises', caloriesPerRep: 0.6 },
    { name: 'Hyperextensions', caloriesPerRep: 0.6 },
    { name: 'Chest Supported Rows', caloriesPerRep: 0.7 },
    { name: 'Rack Pulls', caloriesPerRep: 1 },
    { name: 'Leg Press Calf Raises', caloriesPerRep: 0.6 },
    { name: 'Roman Chair Leg Raises', caloriesPerRep: 0.7 },
    { name: 'Cable Crunches', caloriesPerRep: 0.7 },
    { name: 'Standing Barbell Calf Raises', caloriesPerRep: 0.6 },
    { name: 'Hyperextensions', caloriesPerRep: 0.6 },
    { name: 'Chest Supported Rows', caloriesPerRep: 0.7 },
    { name: 'Rack Pulls', caloriesPerRep: 1 },
    { name: 'Tricep Kickbacks', caloriesPerRep: 0.6 },
    { name: 'Tricep Pushdowns', caloriesPerRep: 0.7 },
    { name: 'Preacher Curls', caloriesPerRep: 0.6 },
    { name: 'Concentration Curls', caloriesPerRep: 0.6 },
    { name: 'Leg Presses', caloriesPerRep: 0.8 },
    { name: 'Hack Squats', caloriesPerRep: 0.8 },
    { name: 'Pistol Squats', caloriesPerRep: 0.8 },
    { name: 'Sumo Squats', caloriesPerRep: 0.8 },
    { name: 'Split Squats', caloriesPerRep: 0.8 },
    { name: 'Barbell Lunges', caloriesPerRep: 0.8 },
    { name: 'Reverse Lunges', caloriesPerRep: 0.7 },
    { name: 'Deadlift Variations', caloriesPerRep: 0.9 },
    { name: 'Lat Pulldown Variations', caloriesPerRep: 0.8 },
    { name: 'Pull-up Variations', caloriesPerRep: 1 },
    { name: 'Bent Over Row Variations', caloriesPerRep: 0.8 },
    { name: 'Back Flyes', caloriesPerRep: 0.6 },
    { name: 'Reverse Flyes', caloriesPerRep: 0.6 },
    { name: 'Incline Bench Press', caloriesPerRep: 0.7 },
    { name: 'Decline Bench Press', caloriesPerRep: 0.7 },
    { name: 'Dumbbell Pullovers', caloriesPerRep: 0.6 },
    { name: 'Chest Dips', caloriesPerRep: 0.7 },
    { name: 'Chest Fly Variations', caloriesPerRep: 0.7 },
    { name: 'Standing Military Press', caloriesPerRep: 0.8 },
    { name: 'Arnold Press', caloriesPerRep: 0.7 },
    { name: 'Lateral Raises', caloriesPerRep: 0.5 },
    { name: 'Front Raises', caloriesPerRep: 0.6 },
    { name: 'Leg Press Calf Raises', caloriesPerRep: 0.6 },
    { name: 'Seated Calf Raises', caloriesPerRep: 0.6 },
    { name: 'Hyperextensions', caloriesPerRep: 0.6 },
    { name: 'Reverse Hyperextensions', caloriesPerRep: 0.7 },
    { name: 'Cable Crunches', caloriesPerRep: 0.7 },
    { name: 'Russian Twists', caloriesPerRep: 0.5 },
    { name: 'Woodchoppers', caloriesPerRep: 0.7 },
    { name: 'Plank Variations', caloriesPerRep: 0.5 },
    { name: 'Side Planks', caloriesPerRep: 0.5 },
    { name: 'Pike Push-ups', caloriesPerRep: 0.7 },
    { name: 'Diamond Push-ups', caloriesPerRep: 0.6 },
    { name: 'Plyometric Push-ups', caloriesPerRep: 0.8 },
    { name: 'Medicine Ball Slams', caloriesPerRep: 1.2 },
    { name: 'Cable Rows', caloriesPerRep: 0.7 },
    { name: 'T-Bar Rows', caloriesPerRep: 0.8 },
    { name: 'Straight Arm Pulldowns', caloriesPerRep: 0.6 },
    { name: 'Close Grip Pulldowns', caloriesPerRep: 0.7 },
    { name: 'Hyperextensions', caloriesPerRep: 0.6 },
    { name: 'Reverse Hyperextensions', caloriesPerRep: 0.7 },
    { name: 'Cable Crunches', caloriesPerRep: 0.7 },
    { name: 'Russian Twists', caloriesPerRep: 0.5 },
    { name: 'Woodchoppers', caloriesPerRep: 0.7 },
    { name: 'Plank Variations', caloriesPerRep: 0.5 },
    { name: 'Side Planks', caloriesPerRep: 0.5 },
    { name: 'Pike Push-ups', caloriesPerRep: 0.7 },
    { name: 'Diamond Push-ups', caloriesPerRep: 0.6 },
    { name: 'Plyometric Push-ups', caloriesPerRep: 0.8 },
    { name: 'Medicine Ball Slams', caloriesPerRep: 1.2 },
    { name: 'Cable Rows', caloriesPerRep: 0.7 },
    { name: 'T-Bar Rows', caloriesPerRep: 0.8 },
    { name: 'Straight Arm Pulldowns', caloriesPerRep: 0.6 },
    { name: 'Close Grip Pulldowns', caloriesPerRep: 0.7 },
    { name: 'Hyperextensions', caloriesPerRep: 0.6 },
    { name: 'Reverse Hyperextensions', caloriesPerRep: 0.7 },
    { name: 'Cable Crunches', caloriesPerRep: 0.7 },
    { name: 'Russian Twists', caloriesPerRep: 0.5 },
    { name: 'Woodchoppers', caloriesPerRep: 0.7 },
    { name: 'Plank Variations', caloriesPerRep: 0.5 },
    { name: 'Side Planks', caloriesPerRep: 0.5 },
    { name: 'Pike Push-ups', caloriesPerRep: 0.7 },
    { name: 'Diamond Push-ups', caloriesPerRep: 0.6 },
    { name: 'Plyometric Push-ups', caloriesPerRep: 0.8 },
    { name: 'Medicine Ball Slams', caloriesPerRep: 1.2 },
    { name: 'Cable Rows', caloriesPerRep: 0.7 },
    { name: 'T-Bar Rows', caloriesPerRep: 0.8 },
    { name: 'Straight Arm Pulldowns', caloriesPerRep: 0.6 },
    { name: 'Close Grip Pulldowns', caloriesPerRep: 0.7 },
    { name: 'Arm Circles', caloriesPerMinute: 5 },
    { name: 'Arm Extensions', caloriesPerRep: 0.6 },
    { name: 'Arm Raises', caloriesPerMinute: 4 },
    { name: 'Arm Pullover', caloriesPerRep: 0.7 },
    { name: 'Arm Swings', caloriesPerMinute: 6 },
    { name: 'Arm Curls', caloriesPerRep: 0.6 },
    { name: 'Arm Press', caloriesPerMinute: 5 },
    { name: 'Arm Flies', caloriesPerRep: 0.7 },
    { name: 'Arm Clap Push-ups', caloriesPerRep: 0.6 },
    { name: 'Arm Twists', caloriesPerMinute: 4 },
    { name: 'Arm Stretches', caloriesPerMinute: 3 },
    { name: 'Arm Rotation', caloriesPerMinute: 5 },
    { name: 'Arm Bar Stretch', caloriesPerMinute: 6 },
    { name: 'Arm Flexion', caloriesPerMinute: 5 },
    { name: 'Arm Curl with Resistance Band', caloriesPerMinute: 5 },
    { name: 'Arm Overhead Extension', caloriesPerMinute: 5 },
    { name: 'Arm Scissors', caloriesPerMinute: 6 },
    { name: 'Arm Hammer Curl', caloriesPerMinute: 5 },
    { name: 'Arm Bar Shoulder Stretch', caloriesPerMinute: 6 },
    { name: 'Arm Wrestling', caloriesPerMinute: 7 },
    { name: 'Arm Stretching with Pole', caloriesPerMinute: 5 },
    { name: 'Arm Bar Guillotine', caloriesPerMinute: 6 },
    { name: 'Arm Drag', caloriesPerMinute: 7 },
    { name: 'Arm Tension Stretch', caloriesPerMinute: 5 },
    { name: 'Arm Tricep Dumbbell Kickback', caloriesPerMinute: 5 },
    { name: 'Arm Side Plank', caloriesPerMinute: 7 },
    { name: 'Arm Circle Stretch', caloriesPerMinute: 5 },
    { name: 'Arm Dive Bomber Push-ups', caloriesPerMinute: 8 },
    { name: 'Arm Close-Grip Push-ups', caloriesPerMinute: 6 },
    { name: 'Arm Shoulder Stretch', caloriesPerMinute: 5 },
    { name: 'Arm Clasp Chest Stretch', caloriesPerMinute: 5 },
    { name: 'Arm Walkout', caloriesPerMinute: 6 },
    { name: 'Arm Figure 8s', caloriesPerMinute: 5 },
    { name: 'Arm Shoulder Press', caloriesPerMinute: 6 },
    { name: 'Arm Stretch with Towel', caloriesPerMinute: 5 },
    { name: 'Arm Tricep Extension', caloriesPerMinute: 5 },
    { name: 'Arm Chest Stretch', caloriesPerMinute: 5 },
    { name: 'Arm Lateral Raise', caloriesPerMinute: 6 },
    { name: 'Arm Around the World', caloriesPerMinute: 5 },
    { name: 'Arm Diamond Push-ups', caloriesPerMinute: 6 },
    { name: 'Arm Doorway Stretch', caloriesPerMinute: 5 },
    { name: 'Arm Dumbbell Bench Press', caloriesPerMinute: 6 },
    { name: 'Arm Chair Dips', caloriesPerMinute: 6 },
    { name: 'Arm Cobra Stretch', caloriesPerMinute: 5 },
    { name: 'Arm Arnold Press', caloriesPerMinute: 6 },
    { name: 'Arm Scapular Push-ups', caloriesPerMinute: 6 },
    { name: 'Arm Cable Flys', caloriesPerMinute: 6 },
    { name: 'Arm Chest Stretch with Wall', caloriesPerMinute: 5 },
    { name: 'Arm Dumbbell Flys', caloriesPerMinute: 6 },
    { name: 'Arm Machine Flys', caloriesPerMinute: 7 },
    { name: 'Arm Kettlebell Bench Press', caloriesPerMinute: 6 },
    { name: 'Arm Resistance Band Flys', caloriesPerMinute: 6 },
];

const foods = [
  { name: 'Apple', calories: 52, nutrients: 'Carbs: 14g, Protein: 0.3g, Fat: 0.2g' },
  { name: 'Banana', calories: 89, nutrients: 'Carbs: 23g, Protein: 1.1g, Fat: 0.3g' },
        { name: 'Orange', calories: 43, nutrients: 'Carbs: 11g, Protein: 1g, Fat: 0.1g' },
        // Add more foods here
        { name: 'Broccoli', calories: 55, nutrients: 'Carbs: 11g, Protein: 3g, Fat: 0.6g' },
        { name: 'Spinach', calories: 23, nutrients: 'Carbs: 4g, Protein: 3g, Fat: 0.4g' },
        { name: 'Kale', calories: 33, nutrients: 'Carbs: 6g, Protein: 3g, Fat: 0.5g' },
        { name: 'Carrot', calories: 41, nutrients: 'Carbs: 10g, Protein: 1g, Fat: 0.2g' },
        { name: 'Bell Pepper', calories: 31, nutrients: 'Carbs: 7g, Protein: 1g, Fat: 0.3g' },
        { name: 'Tomato', calories: 18, nutrients: 'Carbs: 4g, Protein: 1g, Fat: 0.2g' },
        { name: 'Celery', calories: 6, nutrients: 'Carbs: 1g, Protein: 0.3g, Fat: 0.1g' },
        { name: 'Lettuce', calories: 5, nutrients: 'Carbs: 1g, Protein: 0.5g, Fat: 0.1g' },
        { name: 'Zucchini', calories: 33, nutrients: 'Carbs: 6g, Protein: 2g, Fat: 0.3g' },
        { name: 'Eggplant', calories: 25, nutrients: 'Carbs: 6g, Protein: 1g, Fat: 0.2g' },
        { name: 'Onion', calories: 44, nutrients: 'Carbs: 10g, Protein: 1g, Fat: 0.1g' },
        { name: 'Garlic', calories: 149, nutrients: 'Carbs: 33g, Protein: 6g, Fat: 0.5g' },
        { name: 'Ginger', calories: 80, nutrients: 'Carbs: 18g, Protein: 2g, Fat: 1g' },
        { name: 'Potato', calories: 77, nutrients: 'Carbs: 17g, Protein: 2g, Fat: 0.1g' },
        { name: 'Sweet Potato', calories: 86, nutrients: 'Carbs: 20g, Protein: 2g, Fat: 0.1g' },
        { name: 'Butternut Squash', calories: 45, nutrients: 'Carbs: 12g, Protein: 1g, Fat: 0.1g' },
        { name: 'Pumpkin', calories: 26, nutrients: 'Carbs: 7g, Protein: 1g, Fat: 0.1g' },
        { name: 'Quinoa', calories: 120, nutrients: 'Carbs: 21g, Protein: 4g, Fat: 2g' },
        { name: 'Brown Rice', calories: 216, nutrients: 'Carbs: 45g, Protein: 5g, Fat: 2g' },
        { name: 'Oats', calories: 389, nutrients: 'Carbs: 66g, Protein: 17g, Fat: 7g' },
        { name: 'Whole Wheat Bread', calories: 247, nutrients: 'Carbs: 49g, Protein: 10g, Fat: 2g' },
        // Add more foods until there are 50
        { name: 'Chia Seeds', calories: 138, nutrients: 'Carbs: 12g, Protein: 4g, Fat: 9g' },
        { name: 'Flaxseeds', calories: 534, nutrients: 'Carbs: 29g, Protein: 18g, Fat: 42g' },
        { name: 'Sunflower Seeds', calories: 584, nutrients: 'Carbs: 20g, Protein: 21g, Fat: 51g' },
        { name: 'Pumpkin Seeds', calories: 559, nutrients: 'Carbs: 15g, Protein: 30g, Fat: 45g' },
        { name: 'Coconut', calories: 354, nutrients: 'Carbs: 15g, Protein: 3.3g, Fat: 33.5g' },
        { name: 'Peanut Butter', calories: 588, nutrients: 'Carbs: 20g, Protein: 25g, Fat: 50g' },
        { name: 'Almond Butter', calories: 614, nutrients: 'Carbs: 21g, Protein: 24g, Fat: 55g' },
        { name: 'Cashew Butter', calories: 589, nutrients: 'Carbs: 21g, Protein: 17g, Fat: 50g' },
        { name: 'Hummus', calories: 177, nutrients: 'Carbs: 20g, Protein: 7g, Fat: 9g' },
        { name: 'Guacamole', calories: 120, nutrients: 'Carbs: 6g, Protein: 2g, Fat: 10g' },
        { name: 'Salsa', calories: 36, nutrients: 'Carbs: 8g, Protein: 2g, Fat: 0g' },
        { name: 'Tahini', calories: 592, nutrients: 'Carbs: 24g, Protein: 17g, Fat: 50g' },
        { name: 'Raisins', calories: 299, nutrients: 'Carbs: 79g, Protein: 3g, Fat: 0.5g' },
        { name: 'Dates', calories: 282, nutrients: 'Carbs: 75g, Protein: 2g, Fat: 0.5g' },
        { name: 'Prunes', calories: 240, nutrients: 'Carbs: 64g, Protein: 2g, Fat: 0.5g' },
        { name: 'Cranberries', calories: 46, nutrients: 'Carbs: 12g, Protein: 0.4g, Fat: 0.1g' },
        { name: 'Dried Apricots', calories: 241, nutrients: 'Carbs: 63g, Protein: 3g, Fat: 0g' },
        { name: 'Dried Mango', calories: 319, nutrients: 'Carbs: 82g, Protein: 2g, Fat: 1g' },
        { name: 'Dried Pineapple', calories: 341, nutrients: 'Carbs: 89g, Protein: 1g, Fat: 1g' },
        { name: 'Trail Mix', calories: 480, nutrients: 'Carbs: 31g, Protein: 10g, Fat: 36g' },
        { name: 'Beef Jerky', calories: 410, nutrients: 'Carbs: 10g, Protein: 70g, Fat: 7g' },
        { name: 'Turkey Jerky', calories: 300, nutrients: 'Carbs: 16g, Protein: 65g, Fat: 1g' },
        { name: 'Granola', calories: 461, nutrients: 'Carbs: 66g, Protein: 12g, Fat: 17g' },
        { name: 'Coconut Water', calories: 19, nutrients: 'Carbs: 4g, Protein: 0.7g, Fat: 0g' },
        { name: 'Almond Milk', calories: 15, nutrients: 'Carbs: 1g, Protein: 0.5g, Fat: 1g' },
        { name: 'Soy Milk', calories: 33, nutrients: 'Carbs: 2g, Protein: 3.3g, Fat: 1.8g' },
        { name: 'Rice Milk', calories: 47, nutrients: 'Carbs: 9g, Protein: 0.4g, Fat: 0.7g' },
        { name: 'Coconut Milk', calories: 230, nutrients: 'Carbs: 6g, Protein: 2g, Fat: 24g' },
        { name: 'Condensed Milk', calories: 321, nutrients: 'Carbs: 56g, Protein: 7.9g, Fat: 8g' },
        { name: 'Evaporated Milk', calories: 122, nutrients: 'Carbs: 9g, Protein: 8g, Fat: 7g' },
        { name: 'Olive Tapenade', calories: 220, nutrients: 'Carbs: 5g, Protein: 3g, Fat: 22g' },
        { name: 'Honey Mustard', calories: 262, nutrients: 'Carbs: 64g, Protein: 0.6g, Fat: 0.5g' },
        { name: 'Pesto', calories: 400, nutrients: 'Carbs: 2g, Protein: 7g, Fat: 41g' },
        { name: 'Sriracha', calories: 100, nutrients: 'Carbs: 25g, Protein: 1g, Fat: 0.2g' },
        { name: 'Barbecue Sauce', calories: 234, nutrients: 'Carbs: 55g, Protein: 1g, Fat: 0.5g' },
        { name: 'Soy Sauce', calories: 61, nutrients: 'Carbs: 4g, Protein: 9g, Fat: 0g' },
        { name: 'Tabasco Sauce', calories: 17, nutrients: 'Carbs: 4g, Protein: 1g, Fat: 0g' },
        { name: 'Ketchup', calories: 97, nutrients: 'Carbs: 25g, Protein: 2g, Fat: 0g' },
        { name: 'Mayonnaise', calories: 680, nutrients: 'Carbs: 0g, Protein: 0.6g, Fat: 75g' },
        { name: 'Mustard', calories: 66, nutrients: 'Carbs: 6g, Protein: 3g, Fat: 2g' },
        { name: 'Tahini', calories: 89, nutrients: 'Carbs: 3g, Protein: 3g, Fat: 7g' },
        { name: 'Peanut Sauce', calories: 198, nutrients: 'Carbs: 9g, Protein: 5g, Fat: 17g' },
        { name: 'Hoisin Sauce', calories: 227, nutrients: 'Carbs: 53g, Protein: 5g, Fat: 1g' },
        { name: 'Soy Vinaigrette', calories: 151, nutrients: 'Carbs: 2g, Protein: 2g, Fat: 15g' },
        { name: 'Fish Sauce', calories: 300, nutrients: 'Carbs: 0g, Protein: 30g, Fat: 0g' },
        { name: 'Oyster Sauce', calories: 36, nutrients: 'Carbs: 9g, Protein: 1g, Fat: 0g' },
        { name: 'Sweet Chili Sauce', calories: 250, nutrients: 'Carbs: 58g, Protein: 2g, Fat: 0g' },
        { name: 'Plum Sauce', calories: 150, nutrients: 'Carbs: 36g, Protein: 1g, Fat: 0g' },
        { name: 'Sesame Oil', calories: 884, nutrients: 'Carbs: 0g, Protein: 0g, Fat: 100g' },
        { name: 'Vegetable Oil', calories: 884, nutrients: 'Carbs: 0g, Protein: 0g, Fat: 100g' },
        { name: 'Canola Oil', calories: 884, nutrients: 'Carbs: 0g, Protein: 0g, Fat: 100g' },
        { name: 'Corn Oil', calories: 884, nutrients: 'Carbs: 0g, Protein: 0g, Fat: 100g' },
        { name: 'Sesame Seeds', calories: 573, nutrients: 'Carbs: 23g, Protein: 18g, Fat: 49g' },
        { name: 'Flaxseed Oil', calories: 884, nutrients: 'Carbs: 0g, Protein: 0g, Fat: 100g' },
        { name: 'Chia Oil', calories: 900, nutrients: 'Carbs: 0g, Protein: 0g, Fat: 100g' },
        { name: 'Pumpkin Seed Oil', calories: 884, nutrients: 'Carbs: 0g, Protein: 0g, Fat: 100g' },
        { name: 'Walnut Oil', calories: 884, nutrients: 'Carbs: 0g, Protein: 0g, Fat: 100g' },
        { name: 'Almond Oil', calories: 884, nutrients: 'Carbs: 0g, Protein: 0g, Fat: 100g' },
        { name: 'Avocado Oil', calories: 884, nutrients: 'Carbs: 0g, Protein: 0g, Fat: 100g' },
        { name: 'Coconut Oil', calories: 862, nutrients: 'Carbs: 0g, Protein: 0g, Fat: 100g' },
        { name: 'Grape Seed Oil', calories: 884, nutrients: 'Carbs: 0g, Protein: 0g, Fat: 100g' },
        { name: 'Olive Oil', calories: 884, nutrients: 'Carbs: 0g, Protein: 0g, Fat: 100g' },
        { name: 'Rice Bran Oil', calories: 884, nutrients: 'Carbs: 0g, Protein: 0g, Fat: 100g' },
        { name: 'Hamburger', calories: 250, nutrients: 'Carbs: 31g, Protein: 12g, Fat: 10g' },
        { name: 'Cheeseburger', calories: 303, nutrients: 'Carbs: 32g, Protein: 15g, Fat: 14g' },
        { name: 'French Fries', calories: 312, nutrients: 'Carbs: 41g, Protein: 3g, Fat: 15g' },
        { name: 'Chicken Nuggets', calories: 307, nutrients: 'Carbs: 17g, Protein: 18g, Fat: 19g' },
        { name: 'Pizza Slice', calories: 285, nutrients: 'Carbs: 34g, Protein: 14g, Fat: 11g' },
        { name: 'Hot Dog', calories: 151, nutrients: 'Carbs: 13g, Protein: 7g, Fat: 8g' },
        { name: 'Taco', calories: 170, nutrients: 'Carbs: 12g, Protein: 8g, Fat: 9g' },
        { name: 'Burrito', calories: 417, nutrients: 'Carbs: 46g, Protein: 20g, Fat: 17g' },
        { name: 'Chicken Sandwich', calories: 390, nutrients: 'Carbs: 35g, Protein: 22g, Fat: 18g' },
        { name: 'Fish Sandwich', calories: 367, nutrients: 'Carbs: 39g, Protein: 17g, Fat: 15g' },
        { name: 'Milkshake', calories: 250, nutrients: 'Carbs: 34g, Protein: 5g, Fat: 10g' },
        { name: 'Ice Cream Cone', calories: 207, nutrients: 'Carbs: 27g, Protein: 4g, Fat: 10g' },
        { name: 'Onion Rings', calories: 276, nutrients: 'Carbs: 27g, Protein: 3g, Fat: 17g' },
        { name: 'Chicken Wings', calories: 203, nutrients: 'Carbs: 9g, Protein: 15g, Fat: 13g' },
        { name: 'Nachos', calories: 450, nutrients: 'Carbs: 30g, Protein: 14g, Fat: 30g' },
        { name: 'Fried Chicken', calories: 330, nutrients: 'Carbs: 15g, Protein: 20g, Fat: 22g' },
        { name: 'Sub Sandwich', calories: 360, nutrients: 'Carbs: 38g, Protein: 20g, Fat: 15g' },
        { name: 'Soda', calories: 150, nutrients: 'Carbs: 39g, Protein: 0g, Fat: 0g' },
        { name: 'Muffin', calories: 300, nutrients: 'Carbs: 35g, Protein: 5g, Fat: 15g' },
        { name: 'Doughnut', calories: 250, nutrients: 'Carbs: 30g, Protein: 3g, Fat: 15g' },
        { name: 'Fried Rice', calories: 330, nutrients: 'Carbs: 45g, Protein: 8g, Fat: 12g' },
        { name: 'Egg Roll', calories: 200, nutrients: 'Carbs: 20g, Protein: 7g, Fat: 10g' },
        { name: 'Spring Roll', calories: 150, nutrients: 'Carbs: 15g, Protein: 5g, Fat: 8g' },
        { name: 'Fried Shrimp', calories: 200, nutrients: 'Carbs: 10g, Protein: 15g, Fat: 12g' },
        { name: 'Cheese Fries', calories: 400, nutrients: 'Carbs: 35g, Protein: 10g, Fat: 25g' },
        { name: 'Chicken Tenders', calories: 350, nutrients: 'Carbs: 20g, Protein: 25g, Fat: 15g' },
        { name: 'Quesadilla', calories: 300, nutrients: 'Carbs: 20g, Protein: 15g, Fat: 18g' },
        { name: 'Chili Cheese Fries', calories: 500, nutrients: 'Carbs: 40g, Protein: 15g, Fat: 30g' },
        { name: 'Tater Tots', calories: 320, nutrients: 'Carbs: 30g, Protein: 5g, Fat: 20g' },
        { name: 'Pancakes', calories: 250, nutrients: 'Carbs: 30g, Protein: 5g, Fat: 10g' },
        { name: 'Waffles', calories: 300, nutrients: 'Carbs: 35g, Protein: 5g, Fat: 15g' },
        { name: 'Bagel', calories: 300, nutrients: 'Carbs: 60g, Protein: 10g, Fat: 2g' },
        { name: 'Croissant', calories: 230, nutrients: 'Carbs: 20g, Protein: 5g, Fat: 15g' },
        { name: 'Sausage Roll', calories: 350, nutrients: 'Carbs: 25g, Protein: 10g, Fat: 20g' },
        { name: 'Fried Fish', calories: 400, nutrients: 'Carbs: 20g, Protein: 25g, Fat: 25g' },
        { name: 'Mashed Potatoes', calories: 150, nutrients: 'Carbs: 20g, Protein: 2g, Fat: 7g' },
        { name: 'Cole Slaw', calories: 100, nutrients: 'Carbs: 10g, Protein: 1g, Fat: 5g' },
        { name: 'Macaroni Salad', calories: 200, nutrients: 'Carbs: 25g, Protein: 3g, Fat: 10g' },
        { name: 'Corn Dog', calories: 250, nutrients: 'Carbs: 30g, Protein: 7g, Fat: 12g' },
        { name: 'Fish and Chips', calories: 500, nutrients: 'Carbs: 50g, Protein: 25g, Fat: 25g' },
        { name: 'Beef Taco', calories: 200, nutrients: 'Carbs: 20g, Protein: 10g, Fat: 10g' },
        { name: 'Chicken Taco', calories: 180, nutrients: 'Carbs: 15g, Protein: 12g, Fat: 8g' },
        { name: 'Bean Burrito', calories: 300, nutrients: 'Carbs: 35g, Protein: 15g, Fat: 12g' },
        { name: 'Chicken Burrito', calories: 400, nutrients: 'Carbs: 40g, Protein: 20g, Fat: 18g' },
        { name: 'Beef Burrito', calories: 450, nutrients: 'Carbs: 45g, Protein: 25g, Fat: 20g' }
];

const meals = {
    breakfast: [
        { name: 'Oatmeal', calories: 150, nutrients: 'Carbs: 27g, Protein: 5g, Fat: 3g' },
        { name: 'Eggs', calories: 72, nutrients: 'Carbs: 1g, Protein: 6g, Fat: 5g' },
      ],
      lunch: [
        { name: 'Grilled Chicken Salad', calories: 350, nutrients: 'Carbs: 10g, Protein: 35g, Fat: 20g' },
        { name: 'Turkey Sandwich', calories: 250, nutrients: 'Carbs: 30g, Protein: 20g, Fat: 5g' },
      ],
      dinner: [
        { name: 'Steak', calories: 500, nutrients: 'Carbs: 0g, Protein: 45g, Fat: 35g' },
        { name: 'Salmon', calories: 400, nutrients: 'Carbs: 0g, Protein: 40g, Fat: 25g' },
      ],
};

// Helper functions to simulate API calls
const fetchMovements = (search) => {
    return movements.filter(movement => movement.name.toLowerCase().includes(search.toLowerCase()));
  };
  
  const fetchFoods = (search) => {
    return foods.filter(food => food.name.toLowerCase().includes(search.toLowerCase()));
  };
  
  const fetchMeals = (mealType) => {
    return meals[mealType] || [];
  };
  
  app.get('/', (req, res) => {
    res.send('Fitness App Backend');
  });
  
  app.get('/movements', (req, res) => {
    const search = req.query.search || '';
    res.json(fetchMovements(search));
  });
  
  app.get('/foods', (req, res) => {
    const search = req.query.search || '';
    res.json(fetchFoods(search));
  });
  
  app.get('/meals', (req, res) => {
    const mealType = req.query.mealType || 'breakfast';
    res.json(fetchMeals(mealType));
  });
  
  app.listen(port, () => {
    console.log(`Server is running on http://localhost:${port}`);
  });